name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      extraVars:
        description: 'extraVars'
        required: false
      inventory:
        description: 'inventory'
        required: false
      deploymentManifest:
        description: 'deploymentManifest'
        required: false

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Copy selective files based on selected options
      - name: Copy Files
        run: |
          IFS=',' read -ra extraVars <<< "${{ github.event.inputs.extraVars }}"
          IFS=',' read -ra inventory <<< "${{ github.event.inputs.inventory }}"
          IFS=',' read -ra deploymentManifest <<< "${{ github.event.inputs.deploymentManifest }}"
          for source in "${extraVars[@]}" "${inventory[@]}" "${deploymentManifest[@]}"; do
            destination="prod/dedicated/${source#non-prod/dedicated/}"
            echo "Copying selective files from $source to $destination"
            cp -r "${{ github.workspace }}/$source/"{*.json} "${{ github.workspace }}/$destination"
          done
