name: Update and Merge Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select input to update: extraVars, inventory, deploymentManifest'
        required: true
        default: 'extraVars'
        options:
          extraVars: 'Update extraVars'
          inventory: 'Update inventory'
          deploymentManifest: 'Update deploymentManifest'

jobs:
  update_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Input
        id: validate_input
        run: |
          choice="${{ github.event.inputs.choice }}"
          if [[ $choice != "extraVars" && $choice != "inventory" && $choice != "deploymentManifest" ]]; then
            echo "Invalid choice. Please choose one of: extraVars, inventory, deploymentManifest"
            exit 1
          fi
          echo "::set-output name=CHOICE::$choice"

      - name: Update Dropdown Inputs
        id: update_inputs
        run: |
          choice="$CHOICE"
          case $choice in
            "extraVars")
              cp main/non-prod/extraVars/*.json main/prod/extraVars/
              ;;
            "inventory")
              cp main/non-prod/inventory/*.json main/prod/inventory/
              ;;
            "deploymentManifest")
              cp main/non-prod/deploymentManifest/*.json main/prod/deploymentManifest/
              ;;
            *)
              echo "Invalid choice"
              exit 1
              ;;
          esac
          echo "Inputs updated for $choice"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update $CHOICE dropdown inputs"
          branch: update-$CHOICE-inputs
          commit-message: "Update $CHOICE dropdown inputs"
          body: |
            Automated update of $CHOICE dropdown inputs.
          token: ${{ secrets.GITHUB_TOKEN }}

      # Rest of your workflow steps
