name: Update and Merge Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select input to update: extraVars, inventory, deploymentManifest'
        required: true
        default: 'extraVars'
        options:
          extraVars: 'Update extraVars'
          inventory: 'Update inventory'
          deploymentManifest: 'Update deploymentManifest'

  push:
    paths:
      - 'prod/extraVars/*'

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Directories
        run: mkdir -p prod/extraVars prod/inventory prod/deploymentManifest

      - name: Validate Input
        id: validate_input
        run: |
          choice="${{ github.event.inputs.choice }}"
          if [[ $choice != "extraVars" && $choice != "inventory" && $choice != "deploymentManifest" ]]; then
            echo "Invalid choice. Please choose one of: extraVars, inventory, deploymentManifest"
            exit 1
          fi
          echo "::set-output name=CHOICE::$choice"

      - name: Update Inputs
        id: update_inputs
        run: |
          choice="${{ steps.validate_input.outputs.CHOICE }}"
          case $choice in
            "extraVars")
              cp non-prod/extraVars/*.json prod/extraVars/
              ;;
            "inventory")
              cp non-prod/inventory/*.json prod/inventory/
              ;;
            "deploymentManifest")
              cp non-prod/deploymentManifest/*.json prod/deploymentManifest/
              ;;
            *)
              echo "Invalid choice"
              exit 1
              ;;
          esac
          echo "Inputs updated for $choice"

      - name: Git Push
        if: github.event_name == 'push'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated update of $CHOICE dropdown inputs"
          git push origin HEAD

      - name: Create Pull Request
        if: github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update $CHOICE dropdown inputs"
          branch: update-$CHOICE-inputs
          commit-message: "Automated update of $CHOICE dropdown inputs"
          body: |
            Automated update of $CHOICE dropdown inputs.
          token: ${{ secrets.GITHUB_TOKEN }}
