name: Update and Merge Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select input to update: extraVars, inventory, deploymentManifest'
        required: true
        default: 'extraVars'
        options:
          extraVars: 'Update extraVars'
          inventory: 'Update inventory'
          deploymentManifest: 'Update deploymentManifest'

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Input
        id: validate_input
        run: |
          choice="${{ github.event.inputs.choice }}"
          if [[ $choice != "extraVars" && $choice != "inventory" && $choice != "deploymentManifest" ]]; then
            echo "Invalid choice. Please choose one of: extraVars, inventory, deploymentManifest"
            exit 1
          fi
          echo "::set-output name=CHOICE::$choice"

      - name: Update Dropdown Inputs
        id: update_inputs
        run: |
          choice="$CHOICE"
          case $choice in
            "extraVars")
              cp non-prod/extraVars/*.json prod/extraVars/
              ;;
            "inventory")
              cp non-prod/inventory/*.json prod/inventory/
              ;;
            "deploymentManifest")
              cp non-prod/deploymentManifest/*.json prod/deploymentManifest/
              ;;
            *)
              echo "Invalid choice"
              exit 1
              ;;
          esac
          echo "Inputs updated for $choice"

  create_and_merge_pr:
    runs-on: ubuntu-latest
    needs: update_and_merge
    if: github.event.inputs.choice && github.event.inputs.choice != ''

    steps:
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update $CHOICE dropdown inputs"
          branch: update-$CHOICE-inputs
          commit-message: "Update $CHOICE dropdown inputs"
          body: |
            Automated update of $CHOICE dropdown inputs.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Pull Request Approval
        id: wait_for_approval
        if: steps.create_pr.outputs.pull-request-created == 'true'
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pull-request-number }}

      - name: Merge Pull Request
        if: steps.wait_for_approval.outputs.data.mergeable == true
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pull-request-number }}/merge
          headers:
            authorization: ${{ secrets.GITHUB_TOKEN }}
          body: |
            {
              "merge_method": "squash"
            }

      - name: Copy Files to Destination Directory
        if: steps.wait_for_approval.outputs.data.mergeable == true
        run: |
          # Optional: Perform any cleanup or additional steps after merging the PR
          echo "Files copied to destination directory"
