name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      extraVars:
        description: 'extraVars'
        required: false
      inventory:
        description: 'inventory'
        required: false
      deploymentManifest:
        description: 'deploymentManifest'
        required: false

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Create prod/dedicated directories if not exist
        run: |
          mkdir -p prod/dedicated/extraVars
          mkdir -p prod/dedicated/inventory
          mkdir -p prod/dedicated/deploymentManifest

      - name: Copy Files based on option
        run: |
          if [ -n "${{ github.event.inputs.extraVars }}" ]; then
            cp -r non-prod/extraVars/${{ github.event.inputs.extraVars }} prod/extraVars/
          fi
          if [ -n "${{ github.event.inputs.inventory }}" ]; then
            cp -R non-prod/inventory/${{ github.event.inputs.inventory }} prod/inventory/
          fi
          if [ -n "${{ github.event.inputs.deploymentManifest }}" ]; then
            cp -R non-prod/deploymentManifest/${{ github.event.inputs.deploymentManifest }} prod/deploymentManifest/
          fi