name: Manual File Copy

on:
  workflow_dispatch:
    branches: [ main ]
    paths: 
       - 'non-prod/dedicated/extraVars/**'
       - 'prod/dedicated/extraVars/'
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - extraVars
        - deploymentManifest
        - inventory
            
jobs:
  source_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files for extraVars
        run: |
          echo "extraVars Directory Contents:"
          ls -la ./non-prod/dedicated/extraVars/*

      - name: List Files in Destination Directory
        run: |
          echo "Destination Directory Contents:"
          ls -la ./non-prod/dedicated/extraVars/*

      - name: Copy Files
        run: |
          cp -r ./non-prod/dedicated/extraVars/** ./prod/dedicated/extraVars/
              
