name: Manual File Copy

on:
  workflow_dispatch:
    inputs:
      source_path:
        description: 'Source Path'
        required: true
        default: './non-prod/dedicated/extraVars/**'
      destination_path:
        description: 'Destination Path'
        required: true
        default: './prod/dedicated/extraVars/'

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy File
        run: |
          cp "${{ github.workspace }}/${{ github.event.inputs.source_path }}" "${{ github.workspace }}/${{ github.event.inputs.destination_path }}"
