name: Copy Files to Prod

tasks:
  - find:
      paths: "non-prod/dedicated/extraVars"
      recurse: true
    register: extraVar_path
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Source folder (non-prod)'
        options:
        - option1 
        - option2
        - option3
          loop: "{{ extraVar_path.files|filename }}"
      #source-folder:
        required: true
      destination-folder:
        description: 'Destination folder (prod)'
        required: true

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to prod
        run: |
          mkdir -p ${{ inputs.destination-folder }}
          cp -r ${{ inputs.source-folder }}/* ${{ inputs.destination-folder }}