name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      extraVars:
        description: 'extraVars'
        required: true
        default: '.json'

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files based on option
        run: |
          if [ -n "${{ github.event.inputs.extraVars }}" ]; then
            cp -R ./non-prod/dedicated/extraVars/${{ github.event.inputs.extraVars }} ./prod/dedicated/extraVars/
          fi