name: Copy Files to Prod

on:
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Source folder (non-prod)'
	paths:
	- ‘non-prod/dedicated/deploymentManifest/**’
	- ‘non-prod/dedicated/extraVars/**’
	- ‘non-prod/dedicated/inventory/**’
        required: true
      destination-folder:
        description: 'Destination folder (prod)'
	paths:
	- ‘non-prod/dedicated/deploymentManifest/**’
	- ‘non-prod/dedicated/extraVars/**’
	- ‘non-prod/dedicated/inventory/**’
        required: true

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to prod
        run: |
          mkdir -p ${{ inputs.destination-folder }}
          cp -r ${{ inputs.source-folder }}/* ${{ inputs.destination-folder }}