on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy File
      run: |
        cp non-prod/dedicated/extraVars/**
        git add prod/dedicated/extraVars/
        git commit -m "Copy file to destination"
        git push origin branch-name
