name: Copy Files to Prod

on:
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Source folder (non-prod)'
        required: true
        destination-folder:
        description: 'Destination folder (prod)'
        required: true

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to prod
        run: |
          mkdir -p ${{ inputs.destination-folder }}/non-prod/dedicated/deploymentManifest/**
          cp -r ${{ inputs.source-folder }}/non-prod/dedicated/deploymentManifest/** ${{ inputs.destination-folder }}non-prod/dedicated/deploymentManifest/**
