name: Move Code to Prod

on:
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Source folder path
        required: true
        default: 'non-prod/dedicated'
      paths:
      - 'non-prod/deploymentManifests/**'
      destination-folder:
        description: 'Destination folder path'
        required: true
        default: 'prod/dedicated'
      paths:
      - 'prod/deploymentManifests/**'
    workflow_dispatch:

jobs:
  move_to_prod:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create destination folders
      run: |
        mkdir -p ${{ inputs.destination-folder }}/deploymentManifest
        mkdir -p ${{ inputs.destination-folder }}/extraVars
        mkdir -p ${{ inputs.destination-folder }}/inventory

    - name: Move deploymentManifest
      run: mv ${{ inputs.source-folder }}/deploymentManifest/ ${{ inputs.destination-folder }}/deploymentManifest/

    - name: Move extraVars
      run: mv ${{ inputs.source-folder }}/extraVars/ ${{ inputs.destination-folder }}/extraVars/

    - name: Move inventory
      run: mv ${{ inputs.source-folder }}/inventory/ ${{ inputs.destination-folder }}/inventory/