name: Copy Files

on:
  workflow_dispatch:  # Manual trigger

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy extraVars directory
        run: cp -R non-prod/dedicated/extraVars/* prod/dedicated/extraVars/

      - name: List contents of extraVars directory
        run: ls -l prod/dedicated/extraVars/
