name: Manual File Copy

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - extraVars
        - deploymentManifest
        - inventory
            
jobs:
  source_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files for extraVars
        run: |
          echo "extraVars Directory Contents:"
          ls -la "${{ github.event.inputs.source_directory }}"

      - name: List Files in Destination Directory
        run: |
          echo "Destination Directory Contents:"
          ls -la ./non-prod/dedicated/extraVars/*

      - name: Copy Files
        run: |
          sudo scp -r ./non-prod/dedicated/extraVars/*.json ./prod/dedicated/extraVars/

  destination_files:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: copy file to extraVars
        run: |
          cp -r ./non-prod/dedicated/extraVars/*.json ./prod/dedicated/extraVars/
        
