name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      source_directory:
        description: 'Source Directory'
        required: true
        default: './non-prod/dedicated/extraVars/'
      destination_directory:
        description: 'Destination Directory'
        required: true
        default: './prod/dedicated/extraVars/'

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # List files in the source directory for workflow inputs
      - name: List Files in Source Directory
        run: |
          echo "Files in Source Directory:"
          ls -la "${{ github.workspace }}/${{ github.event.inputs.source_directory }}"

      # Copy files from source to destination directory
      - name: Copy Files
        run: |
          cp -r "${{ github.workspace }}/${{ github.event.inputs.source_directory }}/"* "${{ github.workspace }}/${{ github.event.inputs.destination_directory }}"