name: Move Files
 
on:
  push:
    branches: [ main ]
 
jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move all files from source to docs
        run: |
          git mv non-prod/dedicated/extraVars/* prod/dedicated/extraVars
