name: Copy Files

on:
  workflow_dispatch:  # Manual trigger

jobs:
  copy_files:
    runs-on: ubuntu-latest

    inputs:
      source-path:
        description: 'Source directory'
        required: true
        default: 'non-prod/dedicated/extraVars/'
      destination-path:
        description: 'Destination directory'
        required: true
        default: 'prod/dedicated/extraVars/'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List contents of source directory
        run: ls -l ${{ inputs.source-path }}

      - name: Copy files to destination directory
        run: cp -R ${{ inputs.source-path }}/* ${{ inputs.destination-path }}/

      - name: List contents of destination directory
        run: ls -l ${{ inputs.destination-path }}
