name: Copy Files to Prod

# tasks:
#   - find:
#       paths: "non-prod/dedicated/extraVars"
#       recurse: true
#     register: extraVar_path
on:
  workflow_dispatch:
  - find:
      paths: "non-prod/dedicated/extraVars"
      recurse: true
    register: extraVar_path
    inputs:
      choice:
        type: choice
        description: 'Source folder (non-prod)'
        options: "{{ item.0 }}"
        required: true
      destination-folder:
        description: 'Destination folder (prod)'
        required: true
      with_items: "{{ extraVar_path }}"

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to prod
        run: |
          mkdir -p ${{ inputs.destination-folder }}
          cp -r ${{ inputs.source-folder }}/* ${{ inputs.destination-folder }}