name: Copy Files

on:
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Source folder'
        required: true
      destination-folder:
        description: 'Destination folder'
        required: true

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files
        run: |

          mkdir -p ${{ inputs.destination-folder }}
          cp -r ${{ inputs.source-folder }}/deploymentManifest/** ${{ inputs.destination-folder }}/deploymentManifest/**
          cp -r ${{ inputs.source-folder }}/extraVars/** ${{ inputs.destination-folder }}/extraVars/**
          cp -r ${{ inputs.source-folder }}/inventory/** ${{ inputs.destination-folder }}/inventory/**
