name: Manual File Copy

on:
  workflow_dispatch:
    inputs:
      extraVars:
        description:  'extraVars'
        required: true
        paths:
          - '.non-prod/dedicated/extraVars/**'
      deploymentManifest:
        description:  'deploymentManifest'
        required: true
      inventory:
        description:  'inventory'
        required: true
jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Directories
        run: |
          echo "Directories in the main branch:"
          git ls-tree -d --name-only main