name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      extraVars:
        description: 'Select ExtraVars Folder'
        required: true
        options: |
          main/non-prod/dedicated/extraVars/
          main/non-prod/dedicated/inventory/
          main/non-prod/dedicated/deploymentManifest/
      inventory:
        description: 'Select Inventory Folder'
        required: true
        options: |
          main/non-prod/dedicated/extraVars/
          main/non-prod/dedicated/inventory/
          main/non-prod/dedicated/deploymentManifest/
      deploymentManifest:
        description: 'Select DeploymentManifest Folder'
        required: true
        options: |
          main/non-prod/dedicated/extraVars/
          main/non-prod/dedicated/inventory/
          main/non-prod/dedicated/deploymentManifest/

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Copy files based on selected options
      - name: Copy Files
        run: |
          IFS=',' read -ra extraVars <<< "${{ github.event.inputs.extraVars }}"
          IFS=',' read -ra inventory <<< "${{ github.event.inputs.inventory }}"
          IFS=',' read -ra deploymentManifest <<< "${{ github.event.inputs.deploymentManifest }}"
          for source in "${extraVars[@]}" "${inventory[@]}" "${deploymentManifest[@]}"; do
            destination="main/prod/dedicated/${source#main/non-prod/dedicated/}"
            echo "Copying files from $source to $destination"
            cp -r "${{ github.workspace }}/$source/"* "${{ github.workspace }}/$destination"
          done
