name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      paths:
        description: 'Source and Destination Paths (Format: source1:extraVars,source2:inventory)'
        required: true
        default: './non-prod/dedicated/extraVars:extraVars,./non-prod/dedicated/inventory:inventory'

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # List files in the source directories for workflow inputs
      - name: List Files in Source Directories
        id: list_files
        run: |
          IFS=',' read -ra paths <<< "${{ github.event.inputs.paths }}"
          files=()
          for path in "${paths[@]}"; do
            IFS=':' read -ra pair <<< "$path"
            source="${pair[0]}"
            echo "Files in $source:"
            ls -la "$source"
            files+=($(ls -1 "$/$source"))
          done
          echo "::set-output name=files::${files[*]}"

      # Select files to copy
      - name: Select Files
        id: select_files
        run: |
          echo "${{ steps.list_files.outputs.files }}" | tr ' ' '\n' | awk '{print "- " $0}' > files_list.txt
          cat files_list.txt

      # User selects files to copy from the list of files
      - name: Select Files to Copy
        id: select_files_to_copy
        uses: actions/checkout@v2
        with:
          repository: actions/starter-workflows
          path: .github/workflows
          ref: 1.1

      # Copy selected files to the destination directories
      - name: Copy Files
        run: |
          IFS=',' read -ra paths <<< "${{ github.event.inputs.paths }}"
          for path in "${paths[@]}"; do
            IFS=':' read -ra pair <<< "$path"
            source="${pair[0]}"
            destination="${pair[1]}"
            echo "Copying files from $source to $destination"
            cp -r "$/$source/${{ steps.select_files_to_copy.outputs.selected_file }}" "$/$destination/"
          done
