name: Move Files
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Source folder (non-prod)'
        options: 
        
        - option1 
        - option2
        - option3
 
jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move all files from source to docs
        run: |
          git cp -r non-prod/dedicated/extraVars/* prod/dedicated/extraVars
