name: Copy Files

on:
  workflow_dispatch:  # Manual trigger

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create destination directories
        run: mkdir -p ${{ github.workspace }}/prod/dedicated/extraVars ${{ github.workspace }}/prod/dedicated/inventory

      - name: Copy extraVars directory
        run: cp -R non-prod/dedicated/extraVars/* ${{ github.workspace }}/prod/dedicated/extraVars/
        
      - name: Copy inventory directory
        run: cp -R non-prod/dedicated/inventory/* ${{ github.workspace }}/prod/dedicated/inventory/

      - name: List contents of extraVars directory
        run: ls -l ${{ github.workspace }}/prod/dedicated/extraVars/

      - name: List contents of inventory directory
        run: ls -l ${{ github.workspace }}/prod/dedicated/inventory/
