name: Manual File Copy

on:
  workflow_dispatch:
    inputs:
      source_directory:
        description: 'Source Directory'
        required: true
        default: 'main/non-prod/dedicated/extraVars/'
      destination_directory:
        description: 'Destination Directory'
        required: true
        default: 'main/prod/dedicated/extraVars/'

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files
        run: |
          cp -r "${{ github.event.inputs.source_directory }}." "${{ github.event.inputs.destination_directory }}"
