name: Copy Files within Main Branch

on:

  branches:
      - 'main'
  workflow_dispatch:
    inputs:
      extraVars:
        description: 'extraVars'
        required: false
      inventory:
        description: 'inventory'
        required: false
      deploymentManifest:
        description: 'deploymentManifest'
        required: false

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Copy Files based on option
        run: |
          if [ -n "${{ github.event.inputs.extraVars }}" ]; then
            touch test.txt
            touch non-prod/dedicated/extraVars/test.txt
            touch prod/dedicated/extraVars/test.txt
            cp -r non-prod/dedicated/extraVars/${{ github.event.inputs.extraVars }} prod/dedicated/extraVars/
          fi
          if [ -n "${{ github.event.inputs.inventory }}" ]; then
            cp -R non-prod/dedicated/inventory/${{ github.event.inputs.inventory }} prod/dedicated/inventory/
          fi
          if [ -n "${{ github.event.inputs.deploymentManifest }}" ]; then
            cp -R non-prod/dedicated/deploymentManifest/${{ github.event.inputs.deploymentManifest }} prod/dedicated/deploymentManifest/
          fi