name: Manual File Copy

on:
  workflow_dispatch:

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Source and Destination Paths
        id: user_input
        run: |
          echo "::set-output name=non-prod/dedicated/extraVars/**::$(ls -d */)"
          echo "::set-output name=prod/dedicated/*::$(ls -d */)"

      - name: Copy Files
        run: |
          cp -r "${{ steps.user_input.outputs.source_path }}"* "${{ steps.user_input.outputs.destination_path }}"
