name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Destination Folder'
        required: true
          options:
            main/prod/dedicated/extraVars/
            main/prod/dedicated/inventory/
            main/prod/dedicated/deploymentManifest/

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # List files in the selected destination folder for visualization
      - name: List Files in Destination Folder
        run: |
          echo "Files in Destination Folder:"
          ls -la "${{ github.workspace }}/${{ github.event.inputs.choice }}"

      # Copy files based on selected options
      - name: Copy Files
        run: |
          destination="${{ github.event.inputs.choice }}"
          echo "Copying files to $destination"
          # Add your file copying logic here using $destination as the destination folder