name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      option:
        description: 'Choose an option (extraVars, inventory, deploymentManifest)'
        required: true

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files based on option
        run: |
          option="${{ github.event.inputs.option }}"
          case $option in
            extraVars)
              cp -R main/non-prod/dedicated/extraVars/* main/prod/dedicated/extraVars/
              ;;
            inventory)
              cp -R main/non-prod/dedicated/inventory/* main/prod/dedicated/inventory/
              ;;
            deploymentManifest)
              cp -R main/non-prod/dedicated/deploymentManifest/* main/prod/dedicated/deploymentManifest/
              ;;
            *)
              echo "Invalid option selected."
              exit 1
              ;;
          esac
