name: Copy Files within Main Branch

on:
  workflow_dispatch:
    inputs:
      extraVars:
        description: 'extraVars'
        required: true
      inventory:
        description: 'inventory'
        required: true
      deploymentManifest:
        description: 'deploymentManifest'
        required: true

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files based on option
        run: |
          option="${{ github.event.inputs.option }}"
          case $option in
            extraVars)
              cp -R ./non-prod/dedicated/extraVars/* ./prod/dedicated/extraVars/
              ;;
            inventory)
              cp -R ./non-prod/dedicated/inventory/* ./prod/dedicated/inventory/
              ;;
            deploymentManifest)
              cp -R ./non-prod/dedicated/deploymentManifest/* ./prod/dedicated/deploymentManifest/
              ;;
            *)
              echo "Invalid option selected."
              exit 1
              ;;
          esac
