name: Copy Files

on:
  workflow_dispatch:  # Manual trigger

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List contents of source directory
        run: ls -l ${{ github.workspace }}/non-prod/dedicated/extraVars/

      - name: Copy files to destination directory
        run: cp -R ${{ github.workspace }}/non-prod/dedicated/extraVars/* ${{ github.workspace }}/prod/dedicated/extraVars/

      - name: List contents of destination directory
        run: ls -l ${{ github.workspace }}/prod/dedicated/extraVars/
