name: Manual File Copy

on:
  workflow_dispatch:

jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Select Source and Destination Paths
        id: user_input
        run: |
          echo "::set-output name=source_path::./non-prod/dedicated/extraVars/**"
          echo "::set-output name=destination_path::./prod/dedicated/extraVars/"

      - name: List Files in Source Directory
        run: |
          ls -al "${{ steps.user_input.outputs.source_path }}"

      - name: Copy Files
        run: |
          cp -r "${{ steps.user_input.outputs.source_path }}." "${{ steps.user_input.outputs.destination_path }}"
