name: Manual File Copy

on:

  workflow_dispatch:
    inputs:
      extraVars:
        description:  'extraVars'
        required: true
        default: 'null'
      deploymentManifest:
        description:  'deploymentManifest'
        required: true
      inventory:
        description:  'inventory'
        required: true
jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files to folder
        run: |
          cp -r ./non-prod/dedicated/extraVars/* ./prod/dedicated/extraVars/
