name: Manual File Copy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      extraVars:
        description:  'extraVars'
        required: true
        default: 'null'
        paths: './non-prod/dedicated/extraVars/**'
        type: string
      deploymentManifest:
        description:  'deploymentManifest'
        required: true
      inventory:
        description:  'inventory'
        required: true
      release_tag:
        description: 'Release Tag'
        required: true
        type: string
      release_status:
        description: 'Release Status'
        required: true
        default: 'null'
        type: string
      branch_directory:
        description: 'extraVars-'
        required: true
        default: 'main/non/prod/dedicated/extraVars/'
        paths:
          - main/non/prod/dedicated/extraVars/
jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files to folder
        run: |
          cp -r ./non-prod/dedicated/extraVars/* ./prod/dedicated/extraVars/
