name: Copy Files

on:
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Source folder'
        required: true
      destination-folder:
        description: 'Destination folder'
        required: true

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          mkdir -p ${{ inputs.destination-folder }}
          cp -r ${{ inputs.source-folder }}/* ${{ inputs.destination-folder }}
