name: Manual File Copy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      extraVars:
        description:  'extraVars'
        required: true
      deploymentManifest:
        description:  'deploymentManifest'
        required: true
      inventory:
        description:  'inventory'
        required: true
jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files from Branch
        run: |
          cp -r ./non-prod/dedicated/extraVars/* ./prod/dedicated/extraVars/
