name: Manual File Copy

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - extraVars
        - deploymentManifest
        - inventory
      source_directory:
              description: 'extraVars'
      destination_directory:
              description: 'extraVars'
      source_directory:
              description: 'deploymentManifest'
      destination_directory:
              description: 'deploymentManifest'
      source_directory:
              description: 'inventory'
      destination_directory:
              description: 'inventory'
jobs:
  copy_files:
    name: Copy Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files in Source Directory
        run: |
          echo "Source Directory Contents:"
          ls -la "${{ github.event.inputs.source_directory }}"

      - name: List Files in Destination Directory
        run: |
          echo "Destination Directory Contents:"
          ls -la "${{ github.event.inputs.destination_directory }}"

      - name: Copy Files
        run: |
          sudo scp -r "${{ github.event.inputs.source_directory }}/extraVars/*.json "${{ github.event.inputs.destination_directory }}/extraVars/"
